const Images = [
  {image: require('../assets/images/popular_product1.png')},
  {image: require('../assets/images/popular_product1.png')},
  {image: require('../assets/images/popular_product1.png')},
  {image: require('../assets/images/popular_product1.png')},
  {image: require('../assets/images/popular_product1.png')},
];

export const data = [
  {
    id: '1',
    price: 18,
    cost: 25,
    title: 'Amazing Food Place',
    description: ``,
    saleInfo: 'Khuyến mãi đến 30% khi thuê liên tục trong 6 tháng',
    image: Images[0].image,
    rating: 4,
    reviews: 99,
    aims: ['Restaurant', 'Hotel', 'Dineout'],
  },
  {
    id: '2',
    price: 18,
    cost: 25,
    title: 'Second Amazing Food Place',
    description: ``,
    saleInfo: `Khuyến mãi đến 30% khi thuê liên tục trong 6 tháng`,
    image: Images[1].image,
    rating: 5,
    reviews: 102,
    aims: ['Restaurant', 'Fastfood Center', 'Snacks Corner'],
  },
  {
    id: '3',
    price: 18,
    cost: 25,
    title: 'Third Amazing Food Place',
    description: ``,
    saleInfo: `Khuyến mãi đến 30% khi thuê liên tục trong 6 tháng`,
    image: Images[2].image,
    rating: 3,
    reviews: 220,
    aims: ['Restaurant', 'Hotel', 'Dineout'],
  },
  {
    id: '4',
    price: 18,
    cost: 25,
    title: 'Fourth Amazing Food Place',
    description: ``,
    saleInfo: `Khuyến mãi đến 30% khi thuê liên tục trong 6 tháng`,
    image: Images[3].image,
    rating: 4,
    reviews: 48,
    aims: ['Restaurant', 'Fastfood Center', 'Snacks Corner'],
  },
  {
    id: '5',
    price: 18,
    cost: 25,
    title: 'Fifth Amazing Food Place',
    description: ``,
    saleInfo: `Khuyến mãi đến 30% khi thuê liên tục trong 6 tháng`,
    image: Images[4].image,
    rating: 4,
    reviews: 178,
    aims: ['Restaurant', 'Hotel', 'Dineout'],
  },
  {
    id: '6',
    price: 18,
    cost: 25,
    title: 'Amazing Food Place',
    description: ``,
    saleInfo: `Khuyến mãi đến 30% khi thuê liên tục trong 6 tháng`,
    image: Images[0].image,
    rating: 4,
    reviews: 99,
    aims: ['Restaurant', 'Hotel', 'Dineout'],
  },
  {
    id: '7',
    price: 18,
    cost: 25,
    title: 'Second Amazing Food Place',
    description: ``,
    saleInfo: `Khuyến mãi đến 30% khi thuê liên tục trong 6 tháng`,
    image: Images[1].image,
    rating: 5,
    reviews: 102,
    aims: ['Restaurant', 'Fastfood Center', 'Snacks Corner'],
  },
];
