export const allOrders = [
  {
    orderName: 'Razer 13.4" Razer Book Laptop (Mercury White)',
    orderTotal: '300.000 đ',
    orderQuantity: 2,
    orderImage: require('../assets/images/2.jpg'),
    orderStatus: 'dang_thue',
    orderStatusName: 'Đang thuê',
    orderTime: '10/10/2021 - 10/11/2021',
    id: 2,
    price: '150.000 đ/ngày',
    cost: '250.000 đ/ngày',
    title: 'Razer 13.4" Razer Book Laptop (Mercury White)',
    category: 'design',
    image: require('../assets/images/2.jpg'),
    description: '2.8 GHz Intel Core i7 4-Core (11th Gen)',
    rating: 1,
    reviews: 99,
    aims: ['Chơi game', 'Thiết kế', 'Học tập'],
    ram: '16GB of LPDDR4x RAM ',
    cpu: '2.8 GHz Intel Core i7 4-Core (11th Gen)',
    hardDisk: '512GB SSD',
    screen: '13.4" 3840 x 2100 Display',
    week: {
      name: '1 Tuần',
      price: '1.050.000 đ',
      content: '',
      percent: '',
    },
    month1: {
      name: '1 Tháng',
      price: '4.500.000 đ',
      content: '',
      percent: '',
    },
    month3: {
      name: '3 Tháng',
      price: '13.500.000 đ',
      content: '',
      percent: '',
    },
    month6: {
      name: '3 Tháng',
      price: '13.500.000 đ',
      content: 'Áp dụng khuyến mãi',
      percent: '30%',
    },
  },
  {
    orderName: 'Lenovo 15.6" IdeaPad 5',
    orderTotal: '3.000.000 đ',
    orderQuantity: 8,
    orderImage: require('../assets/images/3.jpg'),
    orderStatus: 'da_thue',
    orderStatusName: 'Đã thuê',
    orderTime: '10/10/2021 - 10/12/2021',
    id: 3,
    price: '120.000 đ/ngày',
    cost: '190.000 đ/ngày',
    title: 'Lenovo 15.6" IdeaPad 5',
    category: 'design',
    image: require('../assets/images/3.jpg'),
    description: 'FHD 1920 x 1080 IPS Display',
    rating: 1,
    reviews: 99,
    aims: ['Văn phòng', 'Lập trình', 'Học tập'],
    ram: '16GB DDR4',
    cpu: '2.4 GHz Intel Core i5 Quad-Core 11th Gen',
    hardDisk: '512GB M.2 NVMe PCIe SSD',
    screen: '15.6" FHD 1920 x 1080 IPS Display',
    week: {
      name: '1 Tuần',
      price: '840.000 đ',
      content: '',
      percent: '',
    },
    month1: {
      name: '1 Tháng',
      price: '3.3600.000 đ',
      content: '',
      percent: '',
    },
    month3: {
      name: '3 Tháng',
      price: '10.080.000 đ',
      content: '',
      percent: '',
    },
    month6: {
      name: '3 Tháng',
      price: '10.080.000 đ',
      content: 'Áp dụng khuyến mãi',
      percent: '30%',
    },
  },
  {
    orderName: 'Microsoft 13.5" Multi-Touch Surface',
    orderTotal: '4.000.000 đ',
    orderQuantity: 5,
    orderImage: require('../assets/images/4.jpg'),
    orderStatus: 'dang_xu_ly',
    orderStatusName: 'Đang xử lý',
    orderTime: '1/1/2022 - 10/3/2022',
    id: 4,
    price: '170.000 đ/ngày',
    cost: '200.000 đ/ngày',
    title: 'Microsoft 13.5" Multi-Touch Surface',
    category: 'design',
    image: require('../assets/images/4.jpg'),
    description: '3.0 GHz Intel Core i7 Quad-Core 11th Gen',
    rating: 1,
    reviews: 99,
    aims: ['Văn phòng', 'Lập trình', 'Học tập', 'Chơi game'],
    ram: '16GB LPDDR4X ',
    cpu: '3.0 GHz Intel Core i7 Quad-Core 11th Gen',
    hardDisk: '512GB SSD',
    screen: '13.5" 2256 x 1504 PixelSense Touchscreen',
    week: {
      name: '1 Tuần',
      price: '1.120.000 đ',
      content: '',
      percent: '',
    },
    month1: {
      name: '1 Tháng',
      price: '4.800.000 đ',
      content: '',
      percent: '',
    },
    month3: {
      name: '3 Tháng',
      price: ' 14.000.000 đ',
      content: '',
      percent: '',
    },
    month6: {
      name: '6 Tháng',
      price: ' 14.000.000 đ',
      content: 'Áp dụng khuyến mãi',
      percent: '30%',
    },
  },
];
