const Images = [
  {image: require('../assets/images/2.jpg')},
  {image: require('../assets/images/3.jpg')},
  {image: require('../assets/images/4.jpg')},
  {image: require('../assets/images/5.jpg')},
  {image: require('../assets/images/100.jpg')},
  {image: require('../assets/images/101.jpg')},
  {image: require('../assets/images/102.jpg')},
  {image: require('../assets/images/103.webp')},
  {image: require('../assets/images/104.jpg')},
];

export const products = [
  {
    id: 2,
    price: '100.000 đ/ngày',
    cost: '',
    title: 'Razer 13.4" Razer Book Laptop (Mercury White)',
    category: 'design',
    image: Images[0].image,
    description: '2.8 GHz Intel Core i7 4-Core (11th Gen)',
    rating: 1,
    reviews: 99,
    aims: ['Chơi game', 'Thiết kế', 'Học tập'],
    ram: '16GB of LPDDR4x RAM ',
    cpu: '2.8 GHz Intel Core i7 4-Core (11th Gen)',
    hardDisk: '512GB SSD',
    screen: '13.4" 3840 x 2100 Display',
    week: {
      name: '1 Tuần',
      price: '700.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month1: {
      name: '1 Tháng',
      price: '2.800.000 đ',
      cost: '3.000.000 đ',
      content: '',
      percent: '',
    },
    month3: {
      name: '3 Tháng',
      price: '7.000.000 đ',
      cost: '9.000.000 đ',
      content: '',
      percent: '',
    },
    month6: {
      name: '6 Tháng',
      price: '10.000.000 đ',
      cost: '12.000.000 đ',
      content: '',
      percent: '',
    },
  },
  {
    id: 3,
    price: '80.000 đ/ngày',
    cost: '100.000 đ/ngày',
    title: 'Lenovo 15.6" IdeaPad 5',
    category: 'design',
    image: Images[1].image,
    description: 'FHD 1920 x 1080 IPS Display',
    rating: 1,
    reviews: 99,
    aims: ['Văn phòng', 'Lập trình', 'Học tập'],
    ram: '16GB DDR4',
    cpu: '2.4 GHz Intel Core i5 Quad-Core 11th Gen',
    hardDisk: '512GB M.2 NVMe PCIe SSD',
    screen: '15.6" FHD 1920 x 1080 IPS Display',
    week: {
      name: '1 Tuần',
      price: '400.000 đ',
      cost: '450.000 đ',
      content: '',
      percent: '',
    },
    month1: {
      name: '1 Tháng',
      price: '1.900.00 đ',
      cost: '2.100.000 đ',
      content: '',
      percent: '',
    },
    month3: {
      name: '3 Tháng',
      price: '3.000.000 đ',
      cost: '3.500.000 đ',
      content: '',
      percent: '',
    },
    month6: {
      name: '6 Tháng',
      price: '5.000.000 đ',
      cost: '5.900.000 đ',
      content: '',
      percent: '',
    },
  },
  {
    id: 4,
    price: '50.000 đ/ngày',
    cost: '80.000 đ/ngày',
    title: 'Microsoft 13.5" Multi-Touch Surface',
    category: 'design',
    image: Images[2].image,
    description: '3.0 GHz Intel Core i7 Quad-Core 11th Gen',
    rating: 1,
    reviews: 99,
    aims: ['Văn phòng', 'Lập trình', 'Học tập', 'Chơi game'],
    ram: '16GB LPDDR4X ',
    cpu: '3.0 GHz Intel Core i7 Quad-Core 11th Gen',
    hardDisk: '512GB SSD',
    screen: '13.5" 2256 x 1504 PixelSense Touchscreen',
    week: {
      name: '1 Tuần',
      price: '350.000 đ',
      cost: '450.000 đ',
      content: '',
      percent: '',
    },
    month1: {
      name: '1 Tháng',
      price: '1.500.000 đ',
      cost: '2.000.000 đ',
      content: '',
      percent: '',
    },
    month3: {
      name: '3 Tháng',
      price: '3.000.000 đ',
      cost: '2.800.000 đ',
      content: '',
      percent: '',
    },
    month6: {
      name: '6 Tháng',
      price: ' 5.000.000 đ',
      cost: '6.000.000 đ',
      content: '',
      percent: '',
    },
  },
  {
    id: 5,
    price: ' 40.000 đ/ngày',
    cost: '80.000 đ/ngày',
    title: 'HP 13.3" ProBook x360 435 G8',
    category: 'design',
    image: Images[3].image,
    description: '13.3" 1920 x 1080 IPS Touchscreen',
    rating: 1,
    reviews: 99,
    aims: ['Văn phòng', 'Lập trình', 'Học tập'],
    ram: '8GB DDR4 RAM',
    cpu: '2.6 GHz AMD Ryzen 3 Quad-Core',
    hardDisk: '256GB NVMe SSD',
    screen: '13.3" 1920 x 1080 IPS Touchscreen',
    week: {
      name: '1 Tuần',
      price: '210.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month1: {
      name: '1 Tháng',
      price: '1.200.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month3: {
      name: '3 Tháng',
      price: '3.000.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month6: {
      name: '6 Tháng',
      price: '4.500.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
  },
  {
    id: 100,
    price: '60.000 đ/ngày',
    cost: '',
    title: 'Alienware - m15 R4',
    category: 'school',
    image: Images[4].image,
    description:
      'Mang lại trải nghiệm tốt nhất với phần cứng và công nghệ hiện đại nhất.',
    rating: 4,
    reviews: 15,
    aims: ['Chơi game', 'Thiết kế'],
    ram: '16 GB, 3200MHz',
    cpu: 'i7, 10870H, 2.2GHz',
    graphics: 'NVIDIA GeForce RTX 3070',
    hardDisk: 'SSD 512 GB',
    screen: '15.6", Full HD (1920 x 1080)',
    week: {
      name: '1 Tuần',
      price: '420.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month1: {
      name: '1 Tháng',
      price: '800.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month3: {
      name: '3 Tháng',
      price: '2.000.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month6: {
      name: '6 Tháng',
      price: '4.000.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
  },
  {
    id: 101,
    price: '60.000 đ/ngày',
    cost: '100.000 đ/ngày',
    title: 'HP Natural Silver',
    category: 'school',
    image: Images[5].image,
    description:
      'Hiệu suất đáng tin cậy, khởi động nhanh chóng và bảo mật cao.',
    rating: 3,
    reviews: 22,
    aims: ['Học tập', 'Văn phòng'],
    ram: '8 GB, 3200MHz',
    cpu: 'i5, 1135G7, 2.2GHz',
    graphics: 'Intel Iris Xe Graphics',
    hardDisk: 'SSD 256 GB',
    screen: '15.6", Full HD (1920 x 1080)',
    week: {
      name: '1 Tuần',
      price: '420.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month1: {
      name: '1 Tháng',
      price: '800.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month3: {
      name: '3 Tháng',
      price: '2.000.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month6: {
      name: '6 Tháng',
      price: '4.000.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
  },
  {
    id: 102,
    price: '60.000 đ/ngày',
    cost: '90.000 đ/ngày',
    title: 'Microsoft Surface Laptop Go',
    category: 'school',
    image: Images[6].image,
    description: 'Gọn nhẹ, màn hình chạm và hoạt động liên tục lên tới 13 giờ.',
    rating: 4,
    reviews: 55,
    aims: ['Học tập', 'Văn phòng'],
    ram: '8 GB, 3200MHz',
    cpu: 'i5, 1035G1 , 2.2GHz',
    graphics: 'Intel Iris Xe',
    hardDisk: 'SSD 128 GB',
    screen: '12.4", Full HD (1536 x 1024)',
    week: {
      name: '1 Tuần',
      price: '420.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month1: {
      name: '1 Tháng',
      price: '800.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month3: {
      name: '3 Tháng',
      price: '2.000.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month6: {
      name: '6 Tháng',
      price: '4.000.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
  },
  {
    id: 103,
    price: '110.000 đ/ngày',
    cost: '180.000 đ/ngày',
    title: 'Apple MacBook Air',
    category: 'school',
    image: Images[7].image,
    description: 'Mỏng, nhẹ, machine learning và hiệu năng cao của chip M1.',
    rating: 5,
    reviews: 31,
    aims: ['Văn phòng', 'Thiết kế', 'Học tập'],
    ram: '8 GB, 3200MHz',
    cpu: 'Apple M1',
    graphics: 'Intel Iris Plus',
    hardDisk: 'SSD 256 GB',
    screen: '13.3", Full HD Rentia (2560 x 1600)',
    week: {
      name: '1 Tuần',
      price: '800.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month1: {
      name: '1 Tháng',
      price: '2.000.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month3: {
      name: '3 Tháng',
      price: '4.000.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
    month6: {
      name: '6 Tháng',
      price: '5.500.000 đ',
      cost: '',
      content: '',
      percent: '',
    },
  },
];

export const popularProducts = [
  {
    id: 1,
    name: 'Dell Inspiron 7400 i5 1135G7',
    price: '120.000 đ/ngày',
    image: require('../assets/images/popular_product1.png'),
  },
  {
    id: 2,
    name: 'Dell Gaming G3 i7 10750H (P89F002G3500B)',
    price: '200.000 đ/ngày',
    image: require('../assets/images/popular_product2.jpg'),
  },
];
